[colors.primary]
background = '#000810'
foreground = '#c4c9d4'

[colors.normal]
black = '#181a1f'
red = '#e55561'
green = '#8ebd6b'
yellow = '#e2b86b'
blue = '#4fa6ed'
magenta = '#bf68d9'
cyan = '#48b0bd'
white = '#c4c9d4'

[colors.bright]
black = '#AEB4C1'
red = '#e45649'
green = '#50a14f'
yellow = '#e2b86b'
blue = '#4078f2'
magenta = '#a626a4'
cyan = '#0184bc'
white = '#383a42'
