
[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrainsMonoNLNerdFontMono"
style = "SemiBold"

[font.bold_italic]
family = "JetBrainsMonoNLNerdFontMono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNLNerdFontMono"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNLNerdFontMono"
style = "Regular"

[font]
size = 13

[terminal.shell]
program = "/usr/bin/zsh"

[window]
dynamic_padding=true
opacity = 1

[window.padding]
x = 20
y = 20

[general]
import = ["/home/Sahil/.config/alacritty/theme/lackluster.toml"]

[terminal]
