# import = ["/home/Sahil/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "SemiBold"

[shell]
program = "/usr/bin/zsh"

[window]
opacity = 0.95
dynamic_padding=true
blur = true

[window.padding]
x = 20
y = 20


