# https://coolors.co/090909-dedede-e67b60-60e698-e5e161-6098e6-e86dab-6de2e8
[colors.primary]
background = "#090909"
foreground = "#dedede"

[colors.cursor]
text = "#090909"
cursor = "#dedede"

[colors.normal]
black = "#070707"
red = "#E67B60"
green = "#60E698"
yellow = "#E5E161"
blue = "#6098E6"
magenta = "#E86DAB"
cyan = "#6DE2E8"
white = "#dedede"
